# Generated by Django 5.1.6 on 2025-02-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='hint',
        ),
    ]
