# Generated by Django 5.1.6 on 2025-02-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_userprofile_points_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.CharField(help_text='Kelimeye ait ipucu', max_length=255)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hint', to='game.word')),
            ],
        ),
    ]
